# Generated by Django 3.2 on 2021-05-05 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatisticsScuderia',
        ),
        migrations.RenameField(
            model_name='scuderia',
            old_name='colors',
            new_name='main_color',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='race_distance',
        ),
        migrations.RemoveField(
            model_name='scuderia',
            name='description',
        ),
        migrations.RemoveField(
            model_name='statisticsdriver',
            name='age_validity',
        ),
        migrations.RemoveField(
            model_name='statisticsdriver',
            name='name_dif_teams',
        ),
    ]
