# Generated by Django 3.1.7 on 2021-05-11 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatisticsScuderia',
        ),
        migrations.RenameField(
            model_name='scuderia',
            old_name='colors',
            new_name='main_color',
        ),
        migrations.RenameField(
            model_name='statisticsdriver',
            old_name='nameDriver',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='race_distance',
        ),
        migrations.RemoveField(
            model_name='scuderia',
            name='description',
        ),
        migrations.RemoveField(
            model_name='statisticsdriver',
            name='age_validity',
        ),
        migrations.RemoveField(
            model_name='statisticsdriver',
            name='name_dif_teams',
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
