# Generated by Django 3.2 on 2021-05-11 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_auto_20210505_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statisticsdriver',
            old_name='nameDriver',
            new_name='name',
        ),
    ]
