# Generated by Django 3.1.7 on 2021-05-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0008_auto_20210517_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='img',
        ),
        migrations.AddField(
            model_name='season',
            name='scuderia_champion',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
