# Generated by Django 3.1.7 on 2021-05-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0009_auto_20210517_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='scuderia_champion',
            field=models.CharField(max_length=200),
        ),
    ]
