# Generated by Django 3.1.7 on 2021-04-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('circuit_length', models.IntegerField()),
                ('laps_in_race', models.IntegerField()),
                ('first_gp', models.IntegerField()),
                ('race_distance', models.IntegerField()),
                ('lap_record', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scuderia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('colors', models.CharField(max_length=100)),
                ('principalDriver', models.CharField(max_length=200)),
                ('secondaryDriver', models.CharField(max_length=200)),
                ('num_championships', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StatisticsDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameDriver', models.CharField(max_length=200)),
                ('num_of_championships', models.IntegerField()),
                ('age_validity', models.IntegerField()),
                ('num_dif_teams', models.IntegerField()),
                ('name_dif_teams', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatisticsScuderia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameScuderia', models.CharField(max_length=100)),
                ('age_of_birth', models.IntegerField()),
                ('num_of_championships', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('nationality', models.CharField(max_length=100)),
                ('scuderia', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('num_gp', models.IntegerField()),
                ('num_scuderias', models.IntegerField()),
                ('world_champion', models.CharField(max_length=100)),
            ],
        ),
    ]
