# Generated by Django 3.1.7 on 2021-04-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('circuit_length', models.IntegerField()),
                ('laps_in_race', models.IntegerField()),
                ('first_gp', models.IntegerField()),
                ('race_distance', models.IntegerField()),
                ('lap_record', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Escuderia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('colors', models.CharField(max_length=100)),
                ('principalDriver', models.CharField(max_length=200)),
                ('secondaryDriver', models.CharField(max_length=200)),
                ('num_championships', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticaDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameDriver', models.CharField(max_length=200)),
                ('num_of_championships', models.IntegerField()),
                ('age_validity', models.IntegerField()),
                ('num_dif_teams', models.IntegerField()),
                ('name_dif_teams', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticaScuderia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameScuderia', models.CharField(max_length=100)),
                ('age_of_birth', models.IntegerField()),
                ('num_of_championships', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('nacionality', models.CharField(max_length=100)),
                ('escuderia', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('num_gp', models.IntegerField()),
                ('num_scuderias', models.IntegerField()),
                ('world_champion', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Pages',
        ),
    ]
