# Generated by Django 3.1.7 on 2021-04-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_auto_20210409_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('nationality', models.CharField(max_length=100)),
                ('scuderia', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Circuito',
            new_name='Circuit',
        ),
        migrations.RenameModel(
            old_name='Escuderia',
            new_name='Scuderia',
        ),
        migrations.RenameModel(
            old_name='Temporada',
            new_name='Season',
        ),
        migrations.RenameModel(
            old_name='EstadisticaDriver',
            new_name='StatisticsDriver',
        ),
        migrations.RenameModel(
            old_name='EstadisticaScuderia',
            new_name='StatisticsScuderia',
        ),
        migrations.DeleteModel(
            name='Piloto',
        ),
    ]
