# Generated by Django 3.1.7 on 2021-04-10 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0003_auto_20210410_0018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pilot',
            new_name='Driver',
        ),
    ]
